### ISSUE TITLE
Error: Schema query must be Object Type but got: Root_Query.

### ISSUE THREAD

**Issue by leopku** [rpellerin/graphql-sequelize-schema-generator#5]
After a searching, I found this awesome generator.

But I had an issue when I add `graphql-sequelize-schema-generator` to my project according to readme.

My environment:
```json
    "express": "^4.15.3",
    "express-graphql": "^0.6.7",
    "graphql": "^0.10.5",
    "graphql-relay": "^0.5.2",
    "graphql-sequelize": "^5.4.2",
    "graphql-sequelize-schema-generator": "^0.2.3",
    "lodash": "^4.17.4",
    "mysql2": "^1.4.0",
    "restify": "^5.0.1",
    "sequelize": "^4.4.2"
```

app.js
```js
import { GraphQLSchema } from 'graphql';
import graphqlHTTP from 'express-graphql';
import ExpressBunyan from 'express-bunyan-logger';
import { /* generateModelTypes, */ generateSchema} from 'graphql-sequelize-schema-generator';
import restify from 'restify';
import logger from './util/logger';
import models from './models';

const app = restify.createServer();
const schema = new GraphQLSchema(generateSchema(models));

app.use(ExpressBunyan({
  'name': 'logger',
  streams: [{
    level: 'info',
    stream: process.stdout
  }]
}));

app.post('/graphql', graphqlHTTP({
  schema,
  graphiql: false
}));

app.get('/graphql', graphqlHTTP({
  schema,
  graphiql: true
}));

const port = process.env.PORT ? parseInt(process.env.PORT) : 3300;
app.listen(port, () => logger.info(`now server is listening in port: ${port}`));
```

I can't start it with error:
```
Schema query must be Object Type but got: Root_Query.
```

What's wrong with my project? Any guys would help me?

**Comment by rpellerin** [comment]
Can you please provide me with the full stacktrace?

**Comment by leopku** [comment]
```
/Users/leo/Projects/js/antmall-api/node_modules/graphql/jsutils/invariant.js:19
    throw new Error(message);
    ^

Error: Schema query must be Object Type but got: Root_Query.
    at invariant (/Users/leo/Projects/js/antmall-api/node_modules/graphql/jsutils/invariant.js:19:11)
    at new GraphQLSchema (/Users/leo/Projects/js/antmall-api/node_modules/graphql/type/schema.js:72:88)
    at Object.<anonymous> (/Users/leo/Projects/js/antmall-api/server.js:11:16)
    at Module._compile (module.js:570:32)
    at loader (/Users/leo/.config/yarn/global/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/leo/.config/yarn/global/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
    at Object.<anonymous> (/Users/leo/.config/yarn/global/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by leopku** [comment]
When I switch to [coderReview's fork](/coderReview/graphql-sequelize-schema-generator), it works fine.

**Comment by rpellerin** [comment]
Then I recommend you use their fork until I fix it. You can also help them finish their PR https://github.com/rpellerin/graphql-sequelize-schema-generator/pull/4

**Comment by leopku** [comment]
Ok, I will try later.
